version: '2.3'
services:
  redis:
    container_name: redis
    image: redis:5.0.7-buster
    networks:
      default:
        aliases:
          - redis
    restart: always
    ports:
      - 6379:6379

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      default:
        aliases:
          - grafana
    restart: always
    ports:
      - 3000:3000

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      default:
        aliases:
          - prometheus
    restart: always
    ports:
      - 9090:9090

  base-pipert:
    container_name: base-pipert
    build:
      context: pipe-base/.
    networks:
      default:
        aliases:
          - base-pipert

  pipert:
    container_name: pipert
    build:
      context: .
    networks:
      default:
        aliases:
          - pipert
    depends_on:
      - redis
      - grafana
      - prometheus
      - base-pipert
    environment:
      REDIS_URL: redis://redis:6379/0
      GRAFANA_URL: grafana://grafana:3000/0
      PROMETHEUS_URL: prometheus://prometheus:9000/0
    ports:
      - 5000:5000
    devices:
      - /dev/video0:/dev/video0

